### ISSUE TITLE
jobber non-responsive while job is running.

### ISSUE THREAD

**Issue by montyrwalls** [dshearer/jobber#69] opened 2017-02-28 20:55 UTC
jobber apparently single threads jobs, so while jobs are running the daemon doesn't respond to commands or other jobs.

to test (sample jobber job):
---

#
# jobber test scripts
#
- name: jobber_test.1
  cmd: |
    sleep 300
    exit 0
  time: 0 50 14
  onError: Stop
  notifyOnError: true
  notifyOnFailure: false

# while this is running do 'jobber list or jobber log'

**Comment by dshearer** [comment] 2017-03-08 00:15
I'm sorry, I haven't had time to look into this yet. 

Fwiw, jobber does not single-thread jobs --- each job gets its own thread. So there must be something else very wrong if the daemon isn't responding. 

Dylan

**Comment by dshearer** [comment] 2017-03-09 21:44
Well I can’t reproduce this on my box.  I’m running CentOS 6.8.  What OS are you using?

**Comment by dshearer** [comment] 2017-03-09 21:53
Well I can’t reproduce this on my box.  I’m running CentOS 6.8.  What OS are you using?

**Comment by dshearer** [comment] 2017-03-09 21:58
Well I can’t reproduce this on my box.  I’m running CentOS 6.8.  What OS are you using?On Mar 7, 2017, at 4:14 PM, Dylan Shearer <dylan@nekonya.info> wrote:I'm sorry, I haven't had time to look into this yet. Fwiw, jobber does not single-thread jobs --- each job gets its own thread. So there must be something else very wrong if the daemon isn't responding. DylanOn Feb 28, 2017, at 12:55 PM, montyrwalls <notifications@github.com> wrote:jobber apparently single threads jobs, so while jobs are running the daemon doesn't respond to commands or other jobs.
to test (sample jobber job):

jobber test scripts


name: jobber_test.1
cmd: |
sleep 300
exit 0
time: 0 50 14
onError: Stop
notifyOnError: true
notifyOnFailure: false

while this is running do 'jobber list or jobber log'—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dshearer/jobber","title":"dshearer/jobber","subtitle":"GitHub repository","main_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a></a>","avatar_image_url":"<a href="<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>" class=""><a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a></a>","action":{"name":"Open in GitHub","url":"<a href="<a href="https://github.com/dshearer/jobber" class="">https://github.com/dshearer/jobber</a>" class=""><a href="https://github.com/dshearer/jobber&lt;/a&gt;" class="">https://github.com/dshearer/jobber&lt;/a&gt;</a>"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"jobber non-responsive while job is running. (#69)"}],"action":{"name":"View Issue","url":"<a href="<a href="https://github.com/dshearer/jobber/issues/69" class="">https://github.com/dshearer/jobber/issues/69</a>" class=""><a href="https://github.com/dshearer/jobber/issues/69&lt;/a&gt;" class="">https://github.com/dshearer/jobber/issues/69&lt;/a&gt;</a>"}}}

**Comment by dshearer** [comment] 2017-04-29 04:27
Closing, but please reopen if there's still a problem.

**Closed by dshearer** 2017-04-29 04:27 UTC
Labels: bug
